// Code generated by mkerrors.pl. DO NOT EDIT.

package errors

//go:generate perl mkerrors.pl
// InvalidArgument

type (
	InvalidArgument struct{}
)

var (
	ErrInvalidArgument InvalidArgument
)

func (e *InvalidArgument) Error() string {
	return "invalid argument"
}
